### ISSUE TITLE
tray and overview of a dpp should be closer to actual yaml

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1724]
### Description

atm we show:

<img width="489" alt="image" src="https://github.com/kumahq/kuma-gui/assets/702355/8df39f83-8224-41b6-b52c-592971105197">

In practice the dataplane looks something like:

```yaml
type: Dataplane
mesh: hard drive-0
name: hard drive-b6adee8ce4-5a5f1.card-proxy-0
networking:
  address: 126.140.162.32
  inbound:
    - health:
        ready: false
      port: 7421
      servicePort: 3912
      serviceAddress: 189.159.111.209
      tags:
        kuma.io/protocol: tcp
        kuma.io/service: panel_circuit_svc.mesh:80_internal
    - health:
        ready: false
      port: 7421
      servicePort: 3912
      serviceAddress: 189.159.111.209
      tags:
        kuma.io/protocol: tcp
        kuma.io/service: panel_board_svc.mesh:80_internal
```

We should have panels and overview that displays individual inbounds with their own tags.
Also this would mean that gateways and dataplane tray and overview would be the same.

As a reference a gateway dataplane looks like:

```yaml
type: Dataplane
name: dp-3
mesh: default
networking:
  address: 127.0.0.1
  gateway:
    type: BUILTIN
    tags:
      kuma.io/service: gw-2
```
