### ISSUE TITLE
Show "Zone" column in DPP view

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-gui#1964]
### Description

Today when a resource is synced from the zone to global it has a zone prefix, i.e. `dpp-1` from `zone-1` will have a `zone-1.dpp-1` name on Global.

When https://github.com/kumahq/kuma/pull/8762 is merged, resources from new zones will have a hash suffix, i.e. `dpp-1-z4x4zw4vdfd4v4cb`. All important values like `namespace`, `name`, `zone` that contribute to the hash could be found in `labels`:
```yaml
type: Dataplane
mesh: default
name: dpp-1-z4x4zw4vdfd4v4cb
labels:
  k8s.kuma.io/namespace: kuma-demo
  kuma.io/display-name: dpp-1
  kuma.io/origin: zone
  kuma.io/zone: zone-1
```

Since we're losing the zone prefixes and also `labels` are hidden deep in the `YAML` tab, probably the best way to provide the same UX is to create a "Zone" column in the DPP table view.

Please take into consideration:
* old Zone CPs with `zone-1.dpp-1` names still exist, so the value for the "Zone" column should be taken either from a zone tag or zone prefix
* when GUI runs on Zone CP, DPPs don't have neither a zone prefix or zone label, so we probably shouldn't render the "Zone" column at all
