### ISSUE TITLE
Built-in Gateways: visualize how traffic is routed to destination services using data from the /_rules API

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#2208]
In the built-in gateway detail view, show how traffic coming in through a MeshGateway’s listeners is routed to its corresponding destination services.

**References**:

- https://kuma.io/docs/2.6.x/guides/gateway-builtin
- https://kuma.io/docs/2.6.x/policies/meshhttproute
- https://github.com/kumahq/kuma/issues/9589

## How it works

Initially, what we have in this view is a MeshGateway resource and its listeners. Additionally, we query the `/_rules` API which gives us the routing rules defined for this MeshGateway.

These rules are the result of creating MeshHTTPRoutes policies which target the MeshGateway (e.g. with a top-level targetRef with kind `MeshGateway` and the MeshGateway’s name). They specify rules that decide how the traffic is routed from the listeners to their corresponding destination services (this information is _defined_ in MeshHTTPRoutes but exposed to us here via the `/_rules` API). For example, a rule could specify that only requests with a certain request header are routed to service A while all others are routed to service B.

For determining how a request’s traffic is routed, a listener is always selected first. There are a few rules for selecting a listener: exact hostname match, prefix hostname match, order of listeners. Once a listener is selected, only routes matching this listeners are relevant. Routes only applying to other listeners are not relevant at all.

Furthermore, a MeshGateway can specify `tags` in its listeners and MeshHTTPRoutes can specify tags in their top-level targetRef.

**MeshGateway**:
`/meshes/default/meshgateways/demo-app`

<details>
<summary>YAML</summary>

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  labels:
    kuma.io/origin: zone
  name: demo-app
spec:
  selectors:
  - match:
      kuma.io/service: demo-app_gateway
  conf:
    listeners:
    - hostname: foo.example.com
      port: 80
      protocol: HTTP
    - hostname: bar.example.com
      port: 80
      protocol: HTTP
```

</details>

**MeshHTTPRoute**:
`/meshes/default/meshhttproutes/demo-app.kuma-system`

<details>
<summary>YAML</summary>

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  labels:
    kuma.io/mesh: default
    kuma.io/origin: zone
  name: demo-app
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshGateway
    name: demo-app
  to:
  - targetRef:
      kind: Mesh
    hostnames:
    - foo.example.com
    rules:
    - default:
        backendRefs:
        - kind: MeshService
          name: demo-app_kuma-demo_svc_5000
          weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /
  - targetRef:
      kind: Mesh
    rules:
    - default:
        backendRefs:
        - kind: MeshService
          name: redis_kuma-demo_svc_6379
          weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /
```

</details>

**`/_rules` API response**:
`/meshes/default/meshgateways/demo-app/_rules`

<details>
<summary>YAML</summary>

```yaml
resource:
  mesh: default
  name: demo-app
  type: MeshGateway
rules:
- fromRules: []
  toRules:
  - conf:
      rules:
      - matches:
        - path:
            value: "/"
            type: PathPrefix
        default:
          backendRefs:
          - kind: MeshService
            name: demo-app_kuma-demo_svc_5000
            weight: 1
      hostnames:
      - foo.example.com
    matchers: []
    origin:
    - mesh: default
      name: demo-app.kuma-system
      type: MeshHTTPRoute
  - conf:
      rules:
      - matches:
        - path:
            value: "/"
            type: PathPrefix
        default:
          backendRefs:
          - kind: MeshService
            name: redis_kuma-demo_svc_6379
            weight: 1
    matchers: []
    origin:
    - mesh: default
      name: demo-app.kuma-system
      type: MeshHTTPRoute
  type: MeshHTTPRoute
  warnings: []
```

</details>

## Presentation

We’re thinking of a UI that allows a user to select a listener to "drill down" and then show (1) the rules at play and (2) which destination services you’d resolve to based on these individual rules.

I’m adding a screenshot of how this would look from the point of view of the data hierarchy. Per listener on the MeshGateway, we would show one or multiple entries representing the rules relevant for this listener. The thing labeled "Rules" in the screenshot are the criteria that decide whether a given request is routed to the service linked to under the label "Services". That service is the destination service of the traffic, provided the request matches the rules.

![image](https://github.com/kumahq/kuma-gui/assets/5774638/fe539f9b-afc5-4fc1-aba1-69d2a8497678)

## Questions

- **Q**: (1) How does a MeshHTTPRoute apply to only a subset of a MeshGateway’s listeners? (2) Does the `/_rules` API call resolve this or will we have to do some form of filtering on the response in the UI?

  **A**: (1) By matching listeners being specified in `spec.to[].hostnames`. (2) The selected hostnames are available on `rules[].toRules[].conf.hostnames`.

- **Q**: For the purposes of this visualization, the only relevant entries from the `/_rules` API are `toRules` with `type: 'MeshHTTPRoute'`, correct?

  **A**: For the time being, yes. We should also consider MeshTCPRoute and, later, other policy types influencing this view.

- **Q**: In the context of MeshGateway and MeshHTTPRoutes targeting them, can backendRefs have a targetRef.kind other than `MeshService` or `MeshServiceSubset`? I’m asking because I want to know if we need to safe-guard this in some way when creating links (e.g. if we have a `kind: MeshGateway` here we would need to create different links).

  **A**: No, only MeshService and MeshServiceSubset are relevant here.

- **Q**: MeshHTTPRoutes _may_ filter traffic based on hostname (but they don’t have to). We want a UI that groups traffic to destination services by listeners first. (1) I assume that means that routes _without_ hostnames filter apply to all listeners of a MeshGateway, correct? (2) Similarly, I assume that routes with hostnames filter apply to all listeners that don’t specify a hostname (or which specify a matching hostname), correct?

  **A**: Two important parts need to be considered here: (1) a MeshGateway’s listener without `hostname` implicitly has a wildcard hostname meaning requests to all origins can be handled by this listener. (2) a route filtering by hostnames applies to a listener if the intersection with a listener’s hostname is non-zero. In other words, taking point 1 into account, a route filtering by hostnames will always apply to any listener without a hostname (the intersection of the implicit wildcard hostname with any hostnames list is always non-zero). In other _other_ words, a route only _doesn’t_ apply to a listener if it filters by hostnames and the listener doesn’t have a matching (explicit) hostname.

- **Q**: Can `MeshGateway.conf.listeners[].hostname` be set to `'*'` explicitly, and does it mean the same as omitting the field (i.e. no hostname or `hostname: '*'` means any hostname) ?

  **A**: Yes, and yes.

- **Q**: Can `MeshHTTPRoute.spec.to[].hostnames[]` be set to `['*']` explicitly, and does it mean the same as omitting the field (i.e. no hostnames or `hostnames: ['*']` means any hostnames) ?

  **A**: Yes, and yes.

- **Q**: Can `MeshGateway.conf.listeners[].hostname` or `MeshHTTPRoute.spec.to[].hostnames[]` have values like `*.foo.example.org`?

  **A**: Yes, they can.

- **Q**: For each listener, should we only show rules from routes with a top-level targetRef whose tags are a subset of those on the listener?

  **A**: Yes, we should filter rules by tags.

- **Q**: For each listener, should we only show rules from routes whose to targetRef have a hostnames list matching that of the listener?

  **A**: No, we shouldn’t filter rules by hostname.

- **Q**: How do MeshHTTPRoute and MeshTCPRoute policies match a MeshGateway’s listeners?

  **A**: MeshHTTPRoutes match listeners with protocol HTTP or HTTPS; MeshTCPRoutes match listeners with protocol TCP or TLS.

- **Q**: Should we show backendRef weights? If yes, should we also show `weight: 1` (the default)?

  **A**: --
