### ISSUE TITLE
Display MeshHTTPRoute (tcp route probably as well) tags in outbound view

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-gui#2412]
### Description

The below explanation assumes the following MeshHTTPRoute:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
 name: http-route-1
 namespace: kuma-system
 labels:
   kuma.io/mesh: default
spec:
 targetRef:
   kind: MeshService
   name: frontend_kuma-demo_svc_8080
 to:
   - targetRef:
       kind: MeshService
       name: backend_kuma-demo_svc_3001
     rules:
       - matches:
           - path:
               type: Prefix
               value: /
         default:
           backendRefs:
             - kind: MeshServiceSubset
               name: backend_kuma-demo_svc_3001
               tags:
                 version: "v0"
               weight: 90
             - kind: MeshServiceSubset
               name: backend_kuma-demo_svc_3001
               tags:
                 version: "v1"
               weight: 10
```

After merging https://github.com/kumahq/kuma/pull/9768 stats for different splits won't get merged so you can view them in Grafana.

![image](https://github.com/kumahq/kuma-gui/assets/2753650/8ad1cd83-906e-47d5-8a67-c070d26d75b1)

The problem is that there is no easy way to figure out which "Destination service" maps to which split. The hash does not tell us much. If a person copies a hash they can see that it matches one of the outbounds.

![image](https://github.com/kumahq/kuma-gui/assets/2753650/5b0c0e89-67a2-4f66-8b29-950153b36eb7)

But they still don't know what's the difference between them.

---

What I suggest is to add the tags used for the split (v0, v1 in this case) and put them next to the service tag:

![image](https://github.com/kumahq/kuma-gui/assets/2753650/e3ed8fbd-bab4-412d-9d44-8ece89278934)
