### ISSUE TITLE
Support non-transparent proxy outbounds

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2833]
### Description

Currently I don't believe we support non-transparent proxy outbounds anywhere in the GUI. i.e. we don't display them anywhere.

Off the top of my head the only place we show outbounds is in the Dataplane Overview/Visualization, and these are outbounds on services using transparent proxy which are inferred/derived from the Envoy /stats API rather than using outbounds explicitly provided/configured in YAML config.

We should also support non-transparent proxy based outbounds, i.e. those provided via a Dataplane config such as:

```yaml
type: Dataplane
mesh: default
name: dp-wordpress-1
networking:
  address: 10.0.0.1
  inbound:
  - port: 8000
    servicePort: 80
    tags:
      kuma.io/service: wordpress
      kuma.io/protocol: http
  outbound:
  - port: 6379
    tags:
      kuma.io/service: redis
```

Some finer points/queries:

1. Currently this summary panel can already get pretty full of information (see below for screengrab of current state). Therefore, if we are to display Outbounds in the Dataplane Summary panel, then we should probably consider using our "Tabs within summary panels" UX i.e. `[Overview/YAML] [Inbounds] [Outbounds]` 

<img width="1219" alt="Screenshot 2024-08-18 at 18 06 14" src="https://github.com/user-attachments/assets/ada37f24-f8e5-4c3b-bfe1-8c90dc5dd70b">

2. Should we also make sure that the Dataplane Overview Visualization supports both Envoy /stats inferred outbounds _and_ explicit config/yaml defined outbounds?
