### ISSUE TITLE
Policy table should handle omitted top-level targetRefs

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-gui#2934]
### Description

Since Kuma 2.9 it's possible to create policy without the top-level targetRef:
```yaml
type: MeshTimeout
name: mt1
mesh: default
spec:
  to:
    - targetRef:
        kind: MeshService
        name: redis
```
which is an equivalent of:
```yaml
type: MeshTimeout
name: mt1
mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshService
        name: redis
```

In policy table `Target ref` we want to see `Mesh` instead of `–`:
<img width="667" alt="image" src="https://github.com/user-attachments/assets/c29a0579-e8ff-43e4-9893-e4c22e168d77">
