### ISSUE TITLE
When gateway is zone originated, we should by default filter dataplanes by zone of the gateway

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma-gui#2982]
### What happened?

When built in gateway is zone originated, we should filter not only by kuma.io/service but also by kuma.io/zone tag. At the moment when inspecting gateway dataplanes on global we see dataplanes from other zones that this gateway is not affecting  actually

When we install demo app in two zones we will see all dataplanes and zone gateway really only affecting one from its zone:
<img width="1788" alt="Screenshot 2024-09-23 at 12 18 09" src="https://github.com/user-attachments/assets/28d2a508-c712-4080-be59-42838343f943">

**Comment by johncowen** [comment]
Hey @Automaat 👋 

I'm not sure if I understand this issue here, if you could help me get to the bottom of it that would be great.

As far as I'm aware, by default we never filter things by zone. The only way to filter a listing by zone is to either type a `zone:your-zone` into the search field, or click on a "zone badge" from elsewhere in the GUI.

Could you explain further what you are looking to add here? 

Thanks!

**Comment by lahabana** [comment]
Request when fetching the dataplanes: `http://localhost:5681/meshes/default/dataplanes/_overview?tag=kuma.io%2Fservice%3Aangle-0&offset=0&size=50`

Doesn't include zone so if I have 2 MeshGateway like:

```
type: MeshGateway
mesh: default
name: angle-0
creationTime: '2022-01-25T13:55:51.798701+01:00'
modificationTime: '2022-01-25T13:55:51.798701+01:00'
labels:
  kuma.io/display-name: angle-0
  kuma.io/origin: zone
  kuma.io/zone: heartache
selectors:
  - match:
      kuma.io/service: angle-0
      not-kuma.io/service: trick
conf:
  listeners:
    - hostname: cool-patroller.male-tuba.name
      port: 6908
      protocol: HTTP
---
type: MeshGateway
mesh: default
name: angle-0
creationTime: '2022-01-25T13:55:51.798701+01:00'
modificationTime: '2022-01-25T13:55:51.798701+01:00'
labels:
  kuma.io/display-name: angle-0
  kuma.io/origin: zone
  kuma.io/zone: stomachache
selectors:
  - match:
      kuma.io/service: angle-0
      not-kuma.io/service: trick
conf:
  listeners:
    - hostname: cool-patroller.male-tuba.name
      port: 6908
      protocol: HTTP
```

When we first land on: `https://deploy-preview-4070--kuma-gui.netlify.app/gui/meshes/default/gateways/builtin/cricket-6/overview?listener=0` (the builtin gw overview page) we should fetch the mesh gateway object: `/meshes/default/meshgateways/cricket-6`.

With this you'll have interesting stuff to display.
For listing dataplanes, this should use the new filters instead of tag and should follow the logic:

If the meshgateway has a label `kuma.io/origin: zone` then fetch the dataplanes with the label `kuma.io/zone: foo` + the selector of your meshgateway.

**Comment by lahabana** [comment]
For example with the meshGateway:

```
type: MeshGateway
mesh: default
name: kettledrum-0
creationTime: '2022-01-25T13:55:51.798701+01:00'
modificationTime: '2022-01-25T13:55:51.798701+01:00'
labels:
  kuma.io/display-name: kettledrum-0
  kuma.io/origin: zone
  kuma.io/zone: forager
selectors:
  - match:
      kuma.io/service: kettledrum-0
      sock: hyphenation
conf:
  listeners:
    - hostname: lost-porter.deficient-knuckle.name
      port: 99
      protocol: HTTPS
      crossMesh: true
      tls:
        mode: PASSTHROUGH
        certificates:
          - secret: my-gateway-certificate
    - hostname: phony-plastic.dramatic-contractor.com
      port: 35254
      protocol: HTTP
      crossMesh: true
```

You should list DPs by doing:

```
/meshes/foo/dataplanes?filter[kuma.io/zone]=forager&filter[kuma.io/service]=kettledrum-0&filter[sock]=hyphenation
```
