### ISSUE TITLE
Service view is broken with ExtneralService

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-gui#599]
### What happened?

When there is an external service like:
```yaml
type: ExternalService
mesh: default
name: httpbin
networking:
  address: httpbin.org:80
tags:
  kuma.io/protocol: http
  kuma.io/service: backend_es
```

service view returns an error:

![image](https://user-images.githubusercontent.com/12110261/215842751-1094d59e-8a38-4a3c-bef1-eed3e9ff6546.png)

it sends a request to `:5681/meshes/default/external-services/backend_es`, but it should send a request to `http://localhost:5681/meshes/default/external-services/httpbin`
